import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { requireUser } from "@/lib/auth/guards";
import { SectionGuidance } from "@/components/dashboard/SectionGuidance";
import { SubmitButton } from "@/components/ui/SubmitButton";
import { FlashMessage } from "@/components/ui/FlashMessage";

function mondayISO() { const d = new Date(); const day = d.getDay(); const diff = d.getDate() - day + (day === 0 ? -6 : 1); d.setDate(diff); return d.toISOString().slice(0, 10); }
async function finish(error:{message:string}|null,message:string){if(error)redirect(`/dashboard/weekly?error=${encodeURIComponent("That weekly update could not be saved.")}`);revalidatePath("/dashboard/weekly");revalidatePath("/dashboard");redirect(`/dashboard/weekly?saved=${encodeURIComponent(message)}`)}
async function savePlan(formData:FormData){"use server";const user=await requireUser();const supabase=await createClient();const{error}=await supabase.from("weekly_plans").upsert({user_id:user.id,week_start:mondayISO(),most_important_result:String(formData.get("most_important_result")||"").trim(),progress_result:String(formData.get("progress_result")||"").trim(),relief_result:String(formData.get("relief_result")||"").trim(),guardrail:String(formData.get("guardrail")||"").trim(),updated_at:new Date().toISOString()},{onConflict:"user_id,week_start"});await finish(error,"Weekly outcomes saved.")}
async function addAction(formData:FormData){"use server";const user=await requireUser();const supabase=await createClient();const{error}=await supabase.from("weekly_actions").insert({user_id:user.id,week_start:mondayISO(),title:String(formData.get("title")||"").trim(),day_of_week:Number(formData.get("day_of_week")||1),minutes:Number(formData.get("minutes")||30)});await finish(error,"Weekly action added.")}
async function toggleAction(formData:FormData){"use server";const user=await requireUser();const supabase=await createClient();const complete=String(formData.get("complete"))==="true";const{error}=await supabase.from("weekly_actions").update({completed_at:complete?new Date().toISOString():null}).eq("id",String(formData.get("id"))).eq("user_id",user.id);await finish(error,complete?"Action completed.":"Action reopened.")}
async function removeAction(formData:FormData){"use server";const user=await requireUser();const supabase=await createClient();const{error}=await supabase.from("weekly_actions").delete().eq("id",String(formData.get("id"))).eq("user_id",user.id);await finish(error,"Action removed.")}
async function buildWeek(){"use server";const user=await requireUser();const supabase=await createClient();const[{data:profile},{data:goals},{data:steps},{data:career},{data:milestones}]=await Promise.all([supabase.from("profiles").select("primary_focus,biggest_challenge,desired_outcome,available_minutes").eq("id",user.id).maybeSingle(),supabase.from("goals").select("id,title,summary").eq("user_id",user.id).eq("status","active").order("priority").limit(2),supabase.from("goal_steps").select("id,goal_id,title,due_date").eq("user_id",user.id).is("completed_at",null).order("due_date",{ascending:true,nullsFirst:false}).limit(3),supabase.from("career_plans").select("next_milestone,target_role").eq("user_id",user.id).maybeSingle(),supabase.from("career_milestones").select("id,title,target_date").eq("user_id",user.id).neq("status","completed").order("target_date",{ascending:true,nullsFirst:false}).limit(2)]);
const main=goals?.[0]?.title||profile?.desired_outcome||profile?.primary_focus||"Complete one meaningful outcome";const progress=milestones?.[0]?.title||career?.next_milestone||(career?.target_role?`Take one concrete step toward ${career.target_role}`:"Move one long-term goal forward");const relief=profile?.biggest_challenge?`Reduce friction around: ${profile.biggest_challenge}`:"Clear one task that has been taking up mental space";const guardrail=(profile?.available_minutes??30)<45?"Keep daily commitments small enough to finish":"Do not add new priorities until these outcomes are scheduled";
let{error}=await supabase.from("weekly_plans").upsert({user_id:user.id,week_start:mondayISO(),most_important_result:main,progress_result:progress,relief_result:relief,guardrail,updated_at:new Date().toISOString()},{onConflict:"user_id,week_start"});if(error)redirect(`/dashboard/weekly?error=${encodeURIComponent("Joye could not build the weekly plan.")}`);
const suggested=[...(steps||[]).map((s,i)=>({user_id:user.id,week_start:mondayISO(),title:s.title,day_of_week:Math.min(5,i+1),minutes:30,source_type:"goal_step",source_id:s.id})),...(milestones||[]).slice(0,1).map(m=>({user_id:user.id,week_start:mondayISO(),title:m.title,day_of_week:4,minutes:45,source_type:"career_milestone",source_id:m.id}))];if(suggested.length){await supabase.from("weekly_actions").delete().eq("user_id",user.id).eq("week_start",mondayISO()).is("completed_at",null);await supabase.from("weekly_actions").insert(suggested)}await supabase.from("joye_memory").insert({user_id:user.id,memory_type:"weekly_plan",content:{main,progress,relief,guardrail},importance:4});revalidatePath("/dashboard/weekly");revalidatePath("/dashboard");redirect("/dashboard/weekly?built=1")}

export default async function Weekly({searchParams}:{searchParams:Promise<{built?:string;saved?:string;error?:string}>}){const params=await searchParams;const user=await requireUser();const supabase=await createClient();const week=mondayISO();const[{data:plan},{data:actions}]=await Promise.all([supabase.from("weekly_plans").select("*").eq("user_id",user.id).eq("week_start",week).maybeSingle(),supabase.from("weekly_actions").select("*").eq("user_id",user.id).eq("week_start",week).order("day_of_week").order("created_at")]);const outcomeCount=[plan?.most_important_result,plan?.progress_result,plan?.relief_result].filter(Boolean).length;const complete=(actions||[]).filter(a=>a.completed_at).length;const totalMinutes=(actions||[]).reduce((s,a)=>s+Number(a.minutes||0),0);
return <section className="mx-auto max-w-7xl pb-16"><p className="eyebrow">Weekly plan</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Turn the week into a realistic schedule</h1><p className="mt-3 max-w-3xl leading-7 text-black/55">Choose three outcomes, then place the actual actions on days you can complete them.</p>{params.built?<div className="mt-6 rounded-2xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-800">Joye built a starting week from your goals, career roadmap, and available time.</div>:null}<FlashMessage saved={params.saved} error={params.error}/>
<div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Outcomes defined" value={`${outcomeCount}/3`} detail="Core results for this week"/><Metric label="Actions completed" value={`${complete}/${actions?.length||0}`} detail="Scheduled actions finished"/><Metric label="Time planned" value={`${totalMinutes} min`} detail="Across the full week"/><Metric label="Week of" value={new Date(`${week}T12:00:00`).toLocaleDateString()} detail="Monday through Sunday"/></div>
<div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-6"><form action={savePlan} className="card grid gap-5 border-joye-100 p-6 sm:p-8"><div><p className="eyebrow">Weekly outcomes</p><h2 className="mt-2 text-2xl font-semibold">What should be true by Sunday?</h2></div><Field label="The result that makes this week count"><input className="input" name="most_important_result" defaultValue={plan?.most_important_result||""} placeholder="The single most important result"/></Field><Field label="The step that moves your future forward"><input className="input" name="progress_result" defaultValue={plan?.progress_result||""} placeholder="A career, money, learning, or goal milestone"/></Field><Field label="The result that creates relief"><input className="input" name="relief_result" defaultValue={plan?.relief_result||""} placeholder="Something that reduces stress or clears space"/></Field><Field label="Your guardrail"><input className="input" name="guardrail" defaultValue={plan?.guardrail||""} placeholder="What will you say no to this week?"/></Field><div className="flex flex-wrap gap-3"><SubmitButton pendingText="Saving outcomes...">Save weekly outcomes</SubmitButton><SubmitButton formAction={buildWeek} className="button-secondary" pendingText="Building your week...">Build this week for me</SubmitButton></div></form>
<div className="card border-joye-100 p-6 sm:p-8"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Daily actions</p><h2 className="mt-2 text-2xl font-semibold">Your week at a glance</h2></div><p className="text-sm text-black/45">Check actions off as you finish them</p></div><div className="mt-5 grid gap-4 lg:grid-cols-7">{days.map(day=><div key={day.value} className="rounded-2xl bg-joye-50/55 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-joye-700">{day.short}</p><div className="mt-3 space-y-2">{(actions||[]).filter(a=>a.day_of_week===day.value).map(a=><article key={a.id} className="rounded-xl bg-white p-3 shadow-sm"><p className={`text-sm font-medium ${a.completed_at?"line-through text-black/35":""}`}>{a.title}</p><p className="mt-1 text-xs text-black/40">{a.minutes} min</p><div className="mt-3 flex items-center justify-between"><form action={toggleAction}><input type="hidden" name="id" value={a.id}/><input type="hidden" name="complete" value={a.completed_at?"false":"true"}/><button className="text-xs font-semibold text-joye-700">{a.completed_at?"Reopen":"Done"}</button></form><form action={removeAction}><input type="hidden" name="id" value={a.id}/><button className="text-xs text-red-600">Remove</button></form></div></article>)}{!(actions||[]).some(a=>a.day_of_week===day.value)?<p className="text-xs text-black/35">Open</p>:null}</div></div>)}</div>
<form action={addAction} className="mt-6 grid gap-4 rounded-2xl bg-joye-50/60 p-5 sm:grid-cols-3"><Field label="Action"><input className="input" name="title" required placeholder="Study one chapter"/></Field><Field label="Day"><select className="input" name="day_of_week">{days.map(d=><option key={d.value} value={d.value}>{d.name}</option>)}</select></Field><Field label="Estimated minutes"><input className="input" type="number" min="5" step="5" name="minutes" defaultValue="30"/></Field><SubmitButton className="button-primary sm:col-span-3 sm:w-fit" pendingText="Adding action...">Add to week</SubmitButton></form></div></div>
<SectionGuidance title="Weekly Joye" summary={outcomeCount===3?"Your outcomes are clear. The next job is protecting enough calendar space to finish the actions.":"Your week still has open outcomes. Joye can build a starting point from saved goals and career milestones."} reasons={[`${outcomeCount}/3 core outcomes are defined.`,`${complete}/${actions?.length||0} scheduled actions are complete.`,`${totalMinutes} minutes are currently planned.`]} nextStep={(actions||[]).find(a=>!a.completed_at)?.title||"Build or add the first action for this week."}/></div></section>}
const days=[{value:1,name:"Monday",short:"Mon"},{value:2,name:"Tuesday",short:"Tue"},{value:3,name:"Wednesday",short:"Wed"},{value:4,name:"Thursday",short:"Thu"},{value:5,name:"Friday",short:"Fri"},{value:6,name:"Saturday",short:"Sat"},{value:7,name:"Sunday",short:"Sun"}];
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="label">{label}</label>{children}</div>};function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="card border-joye-100 p-5"><p className="text-sm text-black/45">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-black/45">{detail}</p></div>}
